/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/internal/documents/{documentId}/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 분석 문서 청크 + 임베딩 upsert
         * @description (document_id, chunk_index) 기준 idempotent. 벡터 차원이 dim 과 다르면 400.
         */
        put: operations["internalUpsertDocumentEmbeddings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 동의 이력 (최신순) */
        get: operations["listConsents"];
        put?: never;
        /** 동의 제출 (새 row 생성) */
        post: operations["submitConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 세션 히스토리 (US-15) */
        get: operations["listSessions"];
        put?: never;
        /**
         * 세션 생성 (US-13/14)
         * @description mode/jobCategory 필수. contextDocumentIds 로 분석 문서 N개 연결 (US-14). 분석 미완료 문서는 422.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/stream-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 세션 채널 SSE/WS 용 리소스 스코프 stream token */
        post: operations["createSessionStreamToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세션 메시지 시퀀스 (US-20) */
        get: operations["listSessionMessages"];
        put?: never;
        /**
         * 답변 제출 (US-19) + 꼬리질문 자동 트리거
         * @description 직전 INTERVIEWER 메시지에 대한 답변을 INTERVIEWEE 로 INSERT. commit 후 generate.followup 발행.
         */
        post: operations["submitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/messages/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 음성 답변 업로드 + STT/분석 트리거
         * @description multipart/form-data 로 audio 파일 업로드. 응답은 transcribing 상태 메시지. STT 완료 후 SESSION_MESSAGE SSE 로 transcript 가 도착합니다.
         */
        post: operations["submitVoiceAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/messages/voice/stream-begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 실시간 음성 답변 시작 (placeholder 생성)
         * @description WS 오디오 스트림 전에 호출. placeholder 메시지를 만들고 messageId 를 반환. 이 messageId 를 WS 쿼리로 넘긴다.
         */
        post: operations["beginVoiceStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 이력서 목록 */
        get: operations["listResumes"];
        put?: never;
        /**
         * 이력서 PDF 업로드 + 분석 트리거
         * @description multipart/form-data 로 PDF 파일을 받아 S3 저장 → DB row 생성(status=PENDING) → AI 분석 자동 발행. 최대 20MB, application/pdf 만 허용.
         */
        post: operations["uploadResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 등록된 레포 목록 */
        get: operations["listRegisteredRepositories"];
        put?: never;
        /**
         * GitHub 레포 등록 + 분석 트리거
         * @description 사용자의 GitHub 토큰으로 메타를 재확인 후 INSERT. id/fullName 불일치(VALIDATION_ERROR), 비공개 접근 불가(REPO_PRIVATE_NO_ACCESS), 존재하지 않음(REPO_NOT_FOUND), 중복(REPO_ALREADY_REGISTERED) 분기.
         */
        post: operations["registerRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repositoryId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GitHub 메타 재동기화 (US-08)
         * @description GitHub API 로 default_branch/name/url 등을 다시 fetch 해 DB 갱신. last_synced_at 갱신. 분석은 재트리거하지 않음.
         */
        post: operations["syncRepository"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/sessions/{sessionId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** RealTime WS 답변 위임 → 답변 INSERT + 꼬리질문 발행 */
        post: operations["internalSubmitAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/embeddings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * pgvector cosine topK 검색
         * @description queryEmbedding 으로 가장 가까운 청크 topK 반환. documentIds 가 비어 있으면 전체.
         */
        post: operations["internalSearchEmbeddings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/analyses/resume/{resumeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 이력서 분석 강제 트리거 */
        post: operations["internalTriggerResumeAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/analyses/repository/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GitHub 레포 분석 강제 트리거 */
        post: operations["internalTriggerRepositoryAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/ai-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 요청 로그 기록 */
        post: operations["internalRecordAiRequestLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/stream-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create SSE stream token */
        post: operations["createStreamToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh StackUp access token */
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create GitHub OAuth authorization URL */
        post: operations["startGithubLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세션 상세 (US-16) */
        get: operations["getSession"];
        put?: never;
        post?: never;
        /** 세션 soft delete */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        /** 세션 제목/메모 수정 */
        patch: operations["updateSessionMeta"];
        trace?: never;
    };
    "/api/sessions/{sessionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 세션 시작 (READY→IN_PROGRESS) (US-17) */
        patch: operations["startSession"];
        trace?: never;
    };
    "/api/sessions/{sessionId}/interrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 세션 중단 (IN_PROGRESS→INTERRUPTED) (US-17) */
        patch: operations["interruptSession"];
        trace?: never;
    };
    "/api/sessions/{sessionId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 세션 종료 (IN_PROGRESS→COMPLETED) (US-17) */
        patch: operations["endSession"];
        trace?: never;
    };
    "/api/sessions/{sessionId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 세션 취소 (READY→CANCELLED) */
        patch: operations["cancelSession"];
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /**
         * 회원 탈퇴 (soft delete + 모든 refresh token revoke)
         * @description User row 의 is_deleted=true. 모든 refresh_token revoke. GitHub access token 무효화는 사용자가 GitHub Settings 에서 별도 수행.
         */
        delete: operations["deleteCurrentUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 면접 통계 (US-02)
         * @description 신규 사용자(데이터 없음)는 카운트 0, 평균 null, recent 빈 배열.
         */
        get: operations["getCurrentUserStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 세션 종합 피드백 조회 */
        get: operations["getSessionFeedback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/{resumeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 이력서 단건 조회 */
        get: operations["getResume"];
        put?: never;
        post?: never;
        /** 이력서 soft delete */
        delete: operations["deleteResume"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/{repositoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 등록 레포 단건 조회 */
        get: operations["getRepository"];
        put?: never;
        post?: never;
        /** 등록 레포 soft delete */
        delete: operations["deleteRepository"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repositories/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub 후보 레포 목록 (페이지)
         * @description 사용자의 GitHub 토큰으로 owner 레포를 updated 순으로 페이지 조회. 각 항목에 alreadyRegistered 플래그.
         */
        get: operations["listCandidateRepositories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/users/{userId}/github-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사용자 GitHub access token 평문 반환
         * @description GithubTokenCipher 로 복호화한 평문 토큰을 응답. 메모리/로그/이벤트 envelope 등 외부 영속/전송 금지.
         */
        get: operations["internalFetchGithubToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 분석 문서 목록 (filter: resumeId 또는 repositoryId)
         * @description filter 미지정 시 사용자 보유 전체. resumeId/repositoryId 둘 다 지정 시 resumeId 가 우선.
         */
        get: operations["listAnalyzedDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 분석 문서 상세 + presigned MD 다운로드 URL
         * @description documentDownloadUrl 은 10분 TTL presigned. analysis_status 가 ANALYZED 인 경우에만 의미 있음.
         */
        get: operations["getAnalyzedDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/github/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete GitHub OAuth login */
        get: operations["completeGithubLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/consents/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 동의 철회 (최신 활성 row 의 revoked_at 갱신) */
        delete: operations["revokeConsent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout and revoke refresh token */
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChunkRequest: {
            /** Format: int32 */
            chunkIndex?: number;
            chunkText?: string;
            embedding?: number[];
        };
        UpsertRequest: {
            model?: string;
            /** Format: int32 */
            dim?: number;
            chunks: components["schemas"]["ChunkRequest"][];
        };
        UpsertResponse: {
            /** Format: int32 */
            upserted?: number;
        };
        ConsentSubmitRequest: {
            /** @enum {string} */
            consentType: "TOS" | "PRIVACY" | "MARKETING";
            consentVersion: string;
        };
        ConsentResponse: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            consentType?: "TOS" | "PRIVACY" | "MARKETING";
            consentVersion?: string;
            agreed?: boolean;
            /** Format: date-time */
            agreedAt?: string;
            /** Format: date-time */
            revokedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        SessionCreateRequest: {
            title?: string;
            memo?: string;
            /** @enum {string} */
            mode: "TECHNICAL" | "PERSONALITY" | "INTEGRATED";
            /** @enum {string} */
            jobCategory: "FRONTEND" | "BACKEND" | "INFRA" | "DBA";
            /** Format: int32 */
            maxQuestions?: number;
            /** Format: int32 */
            maxDurationMinutes?: number;
            contextDocumentIds?: number[];
        };
        SessionResponse: {
            /** Format: int64 */
            id?: number;
            title?: string;
            memo?: string;
            /** @enum {string} */
            mode?: "TECHNICAL" | "PERSONALITY" | "INTEGRATED";
            /** @enum {string} */
            jobCategory?: "FRONTEND" | "BACKEND" | "INFRA" | "DBA";
            /** Format: int32 */
            maxQuestions?: number;
            /** Format: int32 */
            maxDurationMinutes?: number;
            /** @enum {string} */
            status?: "READY" | "IN_PROGRESS" | "INTERRUPTED" | "COMPLETED" | "CANCELLED";
            /** Format: int32 */
            totalQuestionCount?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            endedAt?: string;
            contextDocumentIds?: number[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        StreamTokenResponse: {
            streamToken?: string;
        };
        MessageSubmitRequest: {
            content: string;
        };
        MessageResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sessionId?: number;
            /** Format: int32 */
            sequenceNumber?: number;
            /** @enum {string} */
            role?: "INTERVIEWER" | "INTERVIEWEE" | "SYSTEM";
            content?: string;
            audioFilePath?: string;
            ttsAudioPath?: string;
            /** @enum {string} */
            ttsStatus?: "NOT_REQUESTED" | "PENDING" | "SUCCEEDED" | "FAILED";
            /** Format: double */
            ttsDurationSec?: number;
            /** Format: int64 */
            parentMessageId?: number;
            /** @enum {string} */
            status?: "CREATED" | "COMPLETED" | "FAILED";
            /** Format: date-time */
            createdAt?: string;
        };
        VoiceStreamBeginResponse: {
            /** Format: int64 */
            messageId?: number;
            /** Format: int64 */
            parentMessageId?: number;
            /** Format: int32 */
            sequenceNumber?: number;
        };
        ResumeResponse: {
            /** Format: int64 */
            id?: number;
            originalFilename?: string;
            filePath?: string;
            /** @enum {string} */
            fileType?: "PDF";
            /** Format: int64 */
            fileSize?: number;
            /** @enum {string} */
            status?: "PENDING" | "ANALYZING" | "ANALYZED" | "FAILED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RegisterRepositoryRequest: {
            /** Format: int64 */
            githubRepoId: number;
            fullName: string;
        };
        RegisteredRepositoryResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            githubRepoId?: number;
            repoName?: string;
            repoFullName?: string;
            repoUrl?: string;
            defaultBranch?: string;
            /** @enum {string} */
            status?: "PENDING" | "ANALYZING" | "ANALYZED" | "FAILED";
            /** Format: date-time */
            lastSyncedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        InternalAnswerSubmitRequest: {
            /** Format: int64 */
            userId: number;
            content: string;
            idempotencyKey?: string;
        };
        SearchRequest: {
            queryEmbedding: number[];
            queryText?: string;
            documentIds?: number[];
            /** Format: int32 */
            topK?: number;
        };
        SearchResponse: {
            hits?: components["schemas"]["SearchResponseHit"][];
        };
        SearchResponseHit: {
            /** Format: int64 */
            documentId?: number;
            /** Format: int32 */
            chunkIndex?: number;
            chunkText?: string;
            /** Format: double */
            distance?: number;
        };
        TriggerRequest: {
            /** Format: int64 */
            userId: number;
        };
        AnalysisHandle: {
            /** Format: int64 */
            analyzedDocumentId?: number;
            /** Format: int64 */
            resumeId?: number;
            /** Format: int64 */
            repositoryId?: number;
        };
        Request: {
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            sessionId?: number;
            requestType: string;
            modelName?: string;
            /** Format: int32 */
            inputTokens?: number;
            /** Format: int32 */
            outputTokens?: number;
            /** Format: int32 */
            latencyMs?: number;
            status: string;
            errorMessage?: string;
        };
        RefreshTokenResponse: {
            /**
             * @description New StackUp JWT access token
             * @example new-our-jwt-access-token
             */
            accessToken?: string;
            /**
             * @description Access token type
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: int64
             * @description Access token TTL in seconds
             * @example 900
             */
            expiresIn?: number;
        };
        GithubLoginResponse: {
            /**
             * @description GitHub OAuth authorization URL
             * @example https://github.com/login/oauth/authorize?client_id=...&redirect_uri=...&scope=read:user%20user:email%20repo&state=generated-state
             */
            authorizationUrl?: string;
            /**
             * @description CSRF protection state value to be verified on callback
             * @example generated-state
             */
            state?: string;
        };
        SessionUpdateRequest: {
            title?: string;
            memo?: string;
        };
        UserProfileResponse: {
            /**
             * Format: int64
             * @description StackUp user id
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description Stable GitHub user id
             * @example 123456
             */
            githubId?: number;
            /**
             * @description GitHub username at login time
             * @example octocat
             */
            githubUsername?: string;
            /**
             * @description Primary GitHub email when available
             * @example octocat@example.com
             */
            email?: string | null;
            /**
             * @description GitHub avatar URL
             * @example https://avatars.githubusercontent.com/u/123456
             */
            avatarUrl?: string | null;
        };
        AverageScores: {
            /** Format: double */
            overall?: number;
            /** Format: double */
            technical?: number;
            /** Format: double */
            logic?: number;
            /** Format: double */
            communication?: number;
        };
        RecentScore: {
            /** Format: int64 */
            sessionId?: number;
            /** Format: double */
            overall?: number;
            /** Format: double */
            technical?: number;
            /** Format: double */
            logic?: number;
            /** Format: double */
            communication?: number;
            /** Format: date-time */
            endedAt?: string;
        };
        UserStatsResponse: {
            /** Format: int64 */
            totalSessionCount?: number;
            /** Format: int64 */
            completedSessionCount?: number;
            averages?: components["schemas"]["AverageScores"];
            recent?: components["schemas"]["RecentScore"][];
        };
        ComponentHealthResponse: {
            name?: string;
            status?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        SystemHealthResponse: {
            status?: string;
            /** Format: date-time */
            timestamp?: string;
            components?: {
                [key: string]: components["schemas"]["ComponentHealthResponse"];
            };
        };
        SystemLiveResponse: {
            status?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        FeedbackResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            sessionId?: number;
            /** Format: double */
            overallScore?: number;
            /** Format: double */
            technicalAccuracy?: number;
            /** Format: double */
            logicScore?: number;
            /** Format: double */
            communicationScore?: number;
            strengthsSummary?: string;
            weaknessesSummary?: string;
            /** @description Improvement keywords returned by AI. The current contract is a string list. */
            improvementKeywords?: string[];
            /** @description Stored report path when AI generates a detailed learning guide/report. */
            reportFilePath?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CandidateRepositoryResponse: {
            /** Format: int64 */
            githubRepoId?: number;
            name?: string;
            fullName?: string;
            htmlUrl?: string;
            defaultBranch?: string;
            isPrivate?: boolean;
            alreadyRegistered?: boolean;
        };
        GithubTokenResponse: {
            accessToken?: string;
        };
        AnalyzedDocumentResponse: {
            /** Format: int64 */
            id?: number;
            sourceType?: string;
            /** Format: int64 */
            sourceId?: number;
            documentPath?: string;
            /** Format: uri */
            documentDownloadUrl?: string;
            summary?: string;
            techStack?: string[];
            /** Format: int32 */
            embeddingChunkCount?: number;
            /** @enum {string} */
            analysisStatus?: "PROCESSING" | "ANALYZED" | "FAILED";
            errorCode?: string;
            errorMessage?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AuthUserResponse: {
            /**
             * Format: int64
             * @description StackUp user id
             * @example 1
             */
            id?: number;
            /**
             * Format: int64
             * @description Stable GitHub user id
             * @example 123456
             */
            githubId?: number;
            /**
             * @description GitHub username at login time
             * @example octocat
             */
            githubUsername?: string;
            /**
             * @description Primary GitHub email when available
             * @example octocat@example.com
             */
            email?: string | null;
            /**
             * @description GitHub avatar URL
             * @example https://avatars.githubusercontent.com/u/123456
             */
            avatarUrl?: string | null;
        };
        GithubCallbackResponse: {
            /**
             * @description StackUp JWT access token
             * @example our-jwt-access-token
             */
            accessToken?: string;
            /**
             * @description Access token type
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: int64
             * @description Access token TTL in seconds
             * @example 900
             */
            expiresIn?: number;
            /** @description Authenticated user profile */
            user?: components["schemas"]["AuthUserResponse"];
            /**
             * @description Whether a new user was created during this login
             * @example false
             */
            isNewUser?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    internalUpsertDocumentEmbeddings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertRequest"];
            };
        };
        responses: {
            /** @description upsert 성공 (응답에 upsert 된 개수 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpsertResponse"];
                };
            };
            /** @description 임베딩 페이로드 검증 실패 (dim 불일치 등) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpsertResponse"];
                };
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpsertResponse"];
                };
            };
            /** @description documentId 에 해당하는 analyzed_documents 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UpsertResponse"];
                };
            };
        };
    };
    listConsents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 이력 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsentResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsentResponse"][];
                };
            };
        };
    };
    submitConsent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentSubmitRequest"];
            };
        };
        responses: {
            /** @description 동의 row 생성 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConsentResponse"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"][];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description 세션 생성 완료 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 요청 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 지정된 문서 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 분석 미완료 문서를 컨텍스트로 지정 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    createSessionStreamToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 토큰 발급 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamTokenResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamTokenResponse"];
                };
            };
            /** @description 세션 없음 / 소유자 아님 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamTokenResponse"];
                };
            };
        };
    };
    listSessionMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 메시지 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"][];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"][];
                };
            };
        };
    };
    submitAnswer: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageSubmitRequest"];
            };
        };
        responses: {
            /** @description 답변 저장 + 꼬리질문 발행 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 세션이 IN_PROGRESS 아니거나 직전 메시지가 질문 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    submitVoiceAnswer: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio: string;
                };
            };
        };
        responses: {
            /** @description 메시지 INSERT + analyze.voice 발행 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 파일 형식/크기 오류 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 세션이 IN_PROGRESS 아니거나 직전 메시지가 질문 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    beginVoiceStream: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description placeholder 생성 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoiceStreamBeginResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoiceStreamBeginResponse"];
                };
            };
            /** @description 세션 상태/직전 메시지 조건 불만족 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VoiceStreamBeginResponse"];
                };
            };
        };
    };
    listResumes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용자 소유 이력서 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"][];
                };
            };
        };
    };
    uploadResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 업로드 + 분석 트리거 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description 빈 파일 / 사이즈 초과 / 비-PDF */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"];
                };
            };
        };
    };
    listRegisteredRepositories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 사용자가 등록한 레포 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"][];
                };
            };
        };
    };
    registerRepository: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRepositoryRequest"];
            };
        };
        responses: {
            /** @description 등록 + 분석 트리거 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description id ↔ fullName 불일치 / 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 비공개 레포 접근 불가 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description GitHub에 해당 레포 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 이미 등록된 레포 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
        };
    };
    syncRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 메타 갱신 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 비공개 레포 접근 불가 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 등록된 레포 또는 GitHub 상 레포 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description GitHub API 호출 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
        };
    };
    internalSubmitAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InternalAnswerSubmitRequest"];
            };
        };
        responses: {
            /** @description 답변 저장 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 세션 없음 / 소유자 불일치 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
            /** @description 세션 IN_PROGRESS 아님 또는 직전이 질문 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    internalSearchEmbeddings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description 검색 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
            /** @description queryEmbedding 누락 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    internalTriggerResumeAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerRequest"];
            };
        };
        responses: {
            /** @description 트리거 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisHandle"];
                };
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisHandle"];
                };
            };
        };
    };
    internalTriggerRepositoryAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerRequest"];
            };
        };
        responses: {
            /** @description 트리거 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisHandle"];
                };
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisHandle"];
                };
            };
        };
    };
    internalRecordAiRequestLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Request"];
            };
        };
        responses: {
            /** @description 기록 큐잉 (fire-and-forget) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createStreamToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamTokenResponse"];
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamTokenResponse"];
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Access token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Refresh token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RefreshTokenResponse"];
                };
            };
        };
    };
    startGithubLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub authorization URL created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubLoginResponse"];
                };
            };
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 세션 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSessionMeta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdateRequest"];
            };
        };
        responses: {
            /** @description 갱신 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 시작됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description READY 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    interruptSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 중단됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description IN_PROGRESS 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    endSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 종료됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description IN_PROGRESS 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    cancelSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description 세션 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
            /** @description READY 아님 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Authentication is required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    deleteCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 탈퇴 처리됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이미 탈퇴한 사용자 */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUserStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 통계 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserStatsResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserStatsResponse"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemHealthResponse"];
                };
            };
        };
    };
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemLiveResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SystemHealthResponse"];
                };
            };
        };
    };
    getSessionFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 피드백 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackResponse"];
                };
            };
            /** @description 세션 또는 피드백 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackResponse"];
                };
            };
        };
    };
    getResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 이력서 메타 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"];
                };
            };
            /** @description 이력서 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumeResponse"];
                };
            };
        };
    };
    deleteResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 이력서 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 레포 메타 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
            /** @description 레포 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RegisteredRepositoryResponse"];
                };
            };
        };
    };
    deleteRepository: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repositoryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 레포 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCandidateRepositories: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub 후보 페이지 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CandidateRepositoryResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CandidateRepositoryResponse"][];
                };
            };
            /** @description GitHub API 호출 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CandidateRepositoryResponse"][];
                };
            };
        };
    };
    internalFetchGithubToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 토큰 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubTokenResponse"];
                };
            };
            /** @description X-Internal-API-Key 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubTokenResponse"];
                };
            };
            /** @description 사용자 없음 또는 토큰 미존재 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubTokenResponse"];
                };
            };
        };
    };
    listAnalyzedDocuments: {
        parameters: {
            query?: {
                resumeId?: number;
                repositoryId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 분석 문서 목록 (documentDownloadUrl 은 비어있음) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalyzedDocumentResponse"][];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalyzedDocumentResponse"][];
                };
            };
        };
    };
    getAnalyzedDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 분석 문서 상세 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalyzedDocumentResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalyzedDocumentResponse"];
                };
            };
            /** @description 분석 문서 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalyzedDocumentResponse"];
                };
            };
        };
    };
    completeGithubLogin: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubCallbackResponse"];
                };
            };
            /** @description GitHub OAuth login failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GithubCallbackResponse"];
                };
            };
        };
    };
    revokeConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "TOS" | "PRIVACY" | "MARKETING";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 철회 처리됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 철회할 활성 동의 없음 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
